name: 'Tagger'
description: 'Creating a new release using the labels from the Pull Request'
author: 'Denis Panfilov'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.
    required: false
    default: ${{ gh.token }}
  pr-number:
    description: PR number
    required: false
    default: ${{ gh.event.number }}
  prefix:
    description: Tag prefix
    required: false
    default: v
  default-tag:
    description: Default tag
    required: false
    default: 0.0.0
  major-tag:
    description: Major tag name
    default: major
  minor-tag:
    description: Minor tag name
    default: minor
  patch-tag:
    description: Patch tag name
    default: patch
runs:
  using: docker
  image: Dockerfile
# runs:
#   using: 'node16'
#   main: 'dist/main/index.js'
#   pre: 'dist/setup/index.js'
branding:
  icon: 'tag'
  color: 'orange'
